name: Auto Merge Specific PRs

on:
  pull_request:
    branches: 
      - master
    types: [opened, synchronize, labeled]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.head.ref, 'changeset-release/master') }}
    steps:
      - name: Auto-merge PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const prNumber = pr.number;

            // Check mergeability
            const { data: updatedPr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber
            });

            if (updatedPr.mergeable) {
              await github.rest.pulls.merge({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: prNumber,
                merge_method: 'squash' // or 'merge' or 'rebase'
              });
              console.log(`PR #${prNumber} merged!`);
            } else {
              console.log(`PR #${prNumber} is not mergeable yet.`);
            }
